### ISSUE TITLE
google form

### ISSUE THREAD

**Issue by arjunmahishi** [arjunmahishi/SRM_NEWS_BOT#1]
The form is not taking in any email ID.
I had made one : https://docs.google.com/forms/d/1s-porzcy0HvT7Z1UvpMIHtl1BWzXKLhw-GjezQ6VGHQ/viewform

But I like your idea of asking what kind of news they prefer

**Comment by xlogix** [comment]
There is a option in Settings which says "Can submit only one response (requires login)". Try opening the link in incognito mode...

**Comment by arjunmahishi** [comment]
oh ya. Yours is not working without loging in.

**Comment by xlogix** [comment]
Try filling out the form...Let me see what happens

**Comment by xlogix** [comment]
Form updated with e-mail address requirement.

**Comment by arjunmahishi** [comment]
I am not able to fill again.

**Comment by xlogix** [comment]
Fixed! Try to fill it now!

**Comment by arjunmahishi** [comment]
filled
